language: php
php: '7.0'
cache:
  directories:
  - node_modules/
  - theme/core/vendor/
env:
  - TRAVIS_NODE_VERSION="6"
addons:
  ssh_known_hosts: 23.229.240.9
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm -v
  - sudo apt-get -qq update
  - sudo apt-get install sshpass
install:
  - npm install
  - composer update
  - composer install
script:
  - npm run build
after_success:
  - echo $TRAVIS_BRANCH
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then sshpass -e rsync -r --delete-after ./theme lukasholzer@23.229.240.9:/home/lukasholzer/websites/robertholzer/; fi
  # - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sshpass -e rsync -r --delete-after ./webapp lukasholzer@23.229.240.9:/var/www/ostern.altwiener-markt.at/html/; fi
  # - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sshpass -e rsync -r --delete-after ./.htaccess lukasholzer@23.229.240.9:/var/www/ostern.altwiener-markt.at/html/; fi
  # - if [[ "$TRAVIS_BRANCH" == "master" ]]; curl https://robertholzer.typeflow.cc/clear_cache/; fi
notifications:
  email:
    recipients: office@lukasholzer.com
    on_success: never
    on_failure: always
