version: '3'

services:

  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - "8080:80"
    restart: always
    links:
      - db:mysql
    volumes:
      - ./data:/data # If mysql database dump is as .sql file inside
      - ./uploads:/app/wp-content/uploads
      - ./theme:/app/wp-content/themes/robertholzer
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      DB_NAME: robertholzer
      DB_HOST: db
      DB_PASS: root
      SERVER_NAME: localhost
      ADMIN_EMAIL: office@lukasholzer.com
      WP_DEBUG: 'true'
      WP_VERSION: latest
      PLUGINS: >-
        [advanced-custom-fields-pro]https://github.com/wp-premium/advanced-custom-fields-pro/archive/master.zip,
        acf-to-rest-api,
        acf-image-crop-add-on,
        wordpress-importer,
        post-types-order,
        [soil]https://github.com/roots/soil/archive/3.7.1.zip,
      THEMES: >-
        [local]robertholzer

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4000:4000" # HMR Server
      - "3000:3000" # BrowserSync
      - "3001:3001" # BrwoserSync Admin interface
    volumes:
      # - ./theme/src:/opt/hmrserver/src
      - ./theme:/opt/hmrserver/theme

  composer:
    restart: 'no'
    image: composer/composer:alpine
    command: install
    volumes:
      - ./theme:/app

  db:
    image: mysql:5.7
    hostname: dbhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80

volumes:
  data:
