version: '3'

services:

  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - "8080:80" # Wordpress
      - "4000:4000" # HMR Server
      - "3000:3000" # BrowserSync
    restart: always
    links:
      - db:mysql
    volumes:
      - ./data:/data # If mysql database dump is as .sql file inside
      - ./app:/var/www/html
      - ./uploads:/app/wp-content/uploads
      - ./theme:/app/wp-content/themes/robertholzer
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/plugins/advanced-custom-fields-pro:/app/wp-content/plugins/advanced-custom-fields-pro
    environment:
      DB_NAME: robertholzer
      DB_HOST: db
      DB_PASS: root
      SERVER_NAME: localhost
      ADMIN_EMAIL: office@lukasholzer.com
      WP_DEBUG: 'true'
      WP_VERSION: latest
      PLUGINS: >-
        [local]advanced-custom-fields-pro,
        acf-image-crop-add-on,
        wordpress-importer,
        [soil]https://github.com/roots/soil/archive/3.7.1.zip,
      THEMES: >-
        [local]robertholzer
    networks:
      - frontend

  frontend-prod:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: frontend-prod
    environment:
      NODE_ENV: production
    networks:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: frontend
    environment:
      NODE_ENV: development
    ports:
      - "4000:4000" # HMR Server
      - "3000:3000" # BrowserSync
      - "3001:3001" # BrwoserSync Admin interface
    volumes:
      # - ./theme/src:/opt/hmrserver/src
      - ./theme:/opt/hmrserver/theme
    networks:
      - frontend

  composer:
    restart: 'no'
    image: composer/composer:alpine
    command: install
    volumes:
      - ./theme:/app

  imageservice:
    image: apsl/thumbor
    ports:
      - "5000:8000"
    volumes:
      - images:/data
    networks:
      - frontend
    environment:
      - ENGINE=graphicsmagick_engine.engine
      - ALLOW_UNSAFE_URL=True
      - AUTO_WEBP=True
      - PROGRESSIVE_JPEG=True

  db:
    image: mysql:5.7
    hostname: dbhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - data:/var/lib/mysql

  wordmove:
    # tty: true
    depends_on:
      - frontend-prod
      - wordpress
    image: mfuezesi/wordmove
    command: bash -c "ls -lah /var/www/html/wp-content/"
    restart: on-failure:5
    container_name: robertholzer_wordmove  # (+)
    environment:
      NODE_ENV: production
    volumes:
      # - ./config:/home
      - ./app:/var/www/html
      - ./uploads:/var/www/html/wp-content/uploads
      - ./theme:/var/www/html/wp-content/themes/robertholzer
      - ~/.ssh:/root/.ssh      # (!)


volumes:
  data:
  app:
  theme:
  uploads:
  images:
    driver: local

networks:
  frontend:
    driver: bridge
